" @ERR []
call fnamemodify('filename', ":.")
call fnamemodify('filename', ":.:h")
call fnamemodify('filename', ":e")
call fnamemodify('filename', ":h")
call fnamemodify('filename', ":h:h")
call fnamemodify('filename', ":h:t")
call fnamemodify('filename', ":p")
call fnamemodify('filename', ":p:h" )
call fnamemodify('filename', ":p:h")
call fnamemodify('filename', ":p:h:h" )
call fnamemodify('filename', ":p:h:h")
call fnamemodify('filename', ":p:h:h:h")
call fnamemodify('filename', ":p:t" )
call fnamemodify('filename', ":p:t")
call fnamemodify('filename', ":r")
call fnamemodify('filename', ":t")
call fnamemodify('filename', ":t:r")
call fnamemodify('filename', ":~")
call fnamemodify('filename', ':.')
call fnamemodify('filename', ':8')
call fnamemodify('filename', ':e')
call fnamemodify('filename', ':gs?[\\/]\+?/?')
call fnamemodify('filename', ':h')
call fnamemodify('filename', ':h:h')
call fnamemodify('filename', ':h:t')
call fnamemodify('filename', ':p')
call fnamemodify('filename', ':p:.')
call fnamemodify('filename', ':p:8')
call fnamemodify('filename', ':p:gs?[\\/]\+?/?')
call fnamemodify('filename', ':p:gs?\\?/?')
call fnamemodify('filename', ':p:gs?\\\+?/?')
call fnamemodify('filename', ':p:h')
call fnamemodify('filename', ':p:h:gs?[\\/]\+?/?')
call fnamemodify('filename', ':p:h:h')
call fnamemodify('filename', ':p:h:h:t')
call fnamemodify('filename', ':p:h:t')
call fnamemodify('filename', ':p:r')
call fnamemodify('filename', ':p:s?[\/]$??')
call fnamemodify('filename', ':p:t')
call fnamemodify('filename', ':p:~')
call fnamemodify('filename', ':r')
call fnamemodify('filename', ':r:s?.*/plugin/??:gs?\W?_?')
call fnamemodify('filename', ':s?/$??:t:s?\c\.git\s*$??')
call fnamemodify('filename', ':s?^[.\/]\+??:p:.')
call fnamemodify('filename', ':t')
call fnamemodify('filename', ':t:r')
call fnamemodify('filename', ':~')
call fnamemodify('filename', ':~:.')
call fnamemodify('filename', ':~:.:h')
call fnamemodify('filename',":h")
call fnamemodify('filename',":p")
call fnamemodify('filename',":r")
call fnamemodify('filename',":t")
call fnamemodify('filename',":~:.")
call fnamemodify('filename',':.')
call fnamemodify('filename',':e')
call fnamemodify('filename',':h')
call fnamemodify('filename',':p')
call fnamemodify('filename',':r')
call fnamemodify('filename',':r:s?\<app/?spec/?')
call fnamemodify('filename',':s?[\/]$??')
call fnamemodify('filename',':s?\<app/?spec/?')
call fnamemodify('filename',':t')
call fnamemodify('filename',':t:r')
